{% set name = "vitaldb" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vitaldb-{{ version }}.tar.gz
  sha256: 7d747631c7e82ebf487d5f47b3665a149018969a74de49435c0518f789718691

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - requests
    - wfdb

test:
  imports:
    - vitaldb
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/vitaldb/vitalutils
  summary: VitalDB Python Libray
  license: MIT
  license_file: LICENSE
  doc_url: https://vitaldb.net/docs/?documentId=1j702xfDef7RNhfZANQQt7tkzzbin2FVe9GAnleDSyzI
  dev_url: https://github.com/vitaldb/vitalutils/tree/master/python/vitaldb-pypi

extra:
  recipe-maintainers:
    - behackl
